version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: solanai
      POSTGRES_USER: solanai
      POSTGRES_PASSWORD: solanai123
  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-data/:/bitnami/redis/data

